language: java
cache:
  directories:
  - "$HOME/.m2"
dist: trusty
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  slack:
    secure: B3kNXu5IXe/xBcW1WaLMJDsYzfIr1LE/er/vQKU6jNNr08C9//6jNnTlQi31EHH/eDAg/Xz0bSAE72R4U6KYE1pWouaWWO62yuhQP6tuyED2/PbNY98ESM6faXcQWYgdOuzoeIb9EUcalcwAL4U5ofVh5pF3EttkuZOr7UoJHNI/Ml0q2RdqvdSbGK5vusU2t/XreCnk6JfoOHgHHpDuBkSLEZVflcFGuutxGUYWhTkzVNAdqqujA93EVjdbZNikMAvTLK7xbEEKGWw7nNq/er7AjTwrCEg/NRAy5HnU/0lCuMGG6xEEXm92AA36wJXi+6lMqYx0OumAbDfetEBXwtRI7YUjnKYkSz8S2Op5Q4drjTa1LiXxn6cY0PaaHkyUW5/mSMAtdZmWddWuz1jnLTugp/oy9Jwmlg7plQE9URuzGxCzBmAfEoMs8dfAjrFzDinq4xiP9vSxF7yn9/0KR5dlrUNQg5juE53YFin/WVZgsvquvRrQniJvIUVIkjwuPizI8z/nLuAR/Hm5SrL8YE6Fd6qCQHDyZR2P/IoscsqcgCsaeyOV5+JGM2Zv8brP4zbM9AeObhrXSDjAehp6hG+0MFYULnf9HnJkyc9BVbfDLbGExB2DRCbwfJAk3zoVepq4Js3VFar4dEB2D03W+dGyiywAPylvIXwd23Dqjk0=
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
env:
  global:
  - secure: VFTkZ4x/5cPGdI91XVnGfH7Se3jwDgh2b0KkFCBabs4zUpOXkPSz621+ebHVr+znH6t+4Jd0wN5WeBmCeiSHZw2clqq5wmwomeVJGaApt6I0INmwTTpDZwr9l/ZlphbCLdR4tH78meeEjTw+u32kBJQvYCGhy0g3zaXLo+QSs/PbSXb/onIM2/8l2+QraVuWthpe2kcXjH6QPIc4m+0vAGCBpi+OJ0mYbvZYT5sNZ6AicZ3U8s19rGTgY3cCB3DLZKOsVAvqB3ldz3YuxpC1WHVOPC/hOkO0gQGYgnNQEiB2HoKl1+dsoZc3BrDi7XrkHJs3vN8d7+CwgW2XCDGq83EA79Ox9DxFKhANNtRDckKXzkWZsqeW4INk5Z+kj1hgj3UHqe6eQh/Fn+EUpbfAbNcFKLHQQ8AdYTbx5EmbFw1DVbWx/PAYcHXxrG2czuzYwd/y50x+q8bXfugyBMVDGcDAjn/Msx3kq4gGk29cwC5EcTiXLkS83n+vYja2aQPdDM5+EtG9CIW5wxyxk4E7N7aXuGfuh/1mfv2WdF7HiQAwTxygM9yxzIH1ZZvVUHI0OZ6uUckbt6UmZUWs+d5W5zut1qEjpzZzO11tTIf9LeifUz9UH1Qh622+/1q2eEuG2AhK/SmJofwHRfO54UuiaZfjdXJLVIRzU7n8kHpiww0=
  - secure: nCBzLoR2Xg8zalQFxbcy+x/F2J9Wx/wgPDBthh2myGJmQ3V9rgJSGk+4CZoJtGqKQutRhmuSusQ9HRK689XxoTseWkPo44bTqC96G1FPd/o2tC2F2JA0q+oVN78krzn+hFFlWdgvOfgIW8Y5Gbb59PMey+TnpIZnz9UA6N39y4xA6igh8pLOYIZYEmqu2q1laKBHIM+lOWYIAAHwrmaZPfelt3JO+PnRr7/HRR0caqZ1JOorLpByDr4kMYvh02ynd/ubmoQjkeUqg5+AMBg79A5itSHsk1jZZFfl4Oe0GdXGl1D5KrcLp1WLKFbNAH8p+AnjhYbvyaB2rzK3s5KenT+EqdFiTqlgY1pR3A3mWmq8wtqULRzgGRx0/Tvd+CnE+IUn1cJo1h+BFt62ZEfQ6ukMiKBlsxtbNsq4Bgo80HhILYrzNpmBMZCg1fJ+R2JBGF5x7o+c7kiOgbUiDdTeiUNtYnydPBrrtX1knUMQBM5fmjSkoIyo1kwrwUxi1r3khcmDvL7USXNKwWj71mS02Fsz2+FoAbfFk7johlcWHwLXkFVkhOA0ScaARSaKy+n2sQNXqyVvZZcAmzq4Zg8GaIwoWVWZZ4GyI8xktE9NJdu3zBiBqN+fXrDoXhapeOMSQMZSyEUmWnV33+t4AYobRVKJwfvCoBuE3n5XTtxOMPo=
  - secure: Z0Jf2dEXgJAJKjQr9P9USL7nF9J4+Te1hyC1lJzOACAuU+e45DNCoDxYI2IKxB5rhzG2uRCxLU4zuT63sLXQRii2JcwTJWSYOQ4jeq9pr2SPXkB5z+ZX3EPie7L5iJOXRY1C44JyUPzqVmNZ+7/PBTNACu21732UWb6pN0QRcePmFspVxKn5Lr8aAHVuJr0388peJIy1eqV1sNXIeilQLdovCnt4xnELUaG5bcV9zpJHNv9vutkMx9rLxB1S/mxHAo0IFF+9QRR6WPoX86d3/ClQRWwPbTGT3qkoL6W41RI3YbAvGacIo85v7DE0HXnDZ/Ov9OZVy0VO0Mt5qnxg+dbRwMhlT8dJfaIT4IM7aGmZBun+Qn/0Mte+OOiQt3a4JPTpQmmQfXwx1HM/vad2qsxSgphBm0Ez4JHqNcDKJGP7ZrbC9hSRVUk7aFMrjMfmyzTNy1oGG7OGvPKMVQbxtA/bWUfgx/e9qsHMDp9hpZqlOEpM5p9MMJurBuUe90To0i/WBWORgrBFlIl9echIynsH8kGAK4JXEpSnhkMpUZIeIG+LGHRdPcNRPE8+RXgyIHb34mnEGkgD6cyX6E1Tlw1wj8HNLdK59R0zb7NW1rcJKjitQC0URhCzGUUKMpcFSffKTL8YC84rKyRpWCs3yhz77kszNVwCRO9TmYKhAGk=
before_install:
- ruby -v
- gem install travis -v 1.8.9 --no-document
- travis version
- export BUILD_NAME=scc-icad-service-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
jobs:
  include:
  - stage: build and deploy
    script:
    - sh scripts/travis/tag_build.sh
    - sh scripts/travis/build_services.sh
    - sh scripts/travis/deploy_to_docker_hub.sh
stages:
  - name: build and deploy
    if: branch = master
