language: java
cache:
  directories:
  - "$HOME/.m2"
dist: trusty
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
  slack:
    secure: N3+kN5RRDPAHXbTYwehdQHtWFU5TXO6PvQJ4g8Ru3RW9CMlKqSqWvQYnvOpf0yhpY03JZlJINks466JRozg6pZftDCTr5NpZw+uofO27oJn6t8tgEcL/Fo9dRmn+ra4z5rABg6JwCp7xjXttqbPCJwqEOojfQf4kQ3YwtM+qLljUrd0YF6ReRzvquCvV0cjvRS5KJDg6ic4YqpRJtwT0rYtclYgveWX1g2PMAU0LP+xUD7Q/CDzV7rZZxpg/LUSbyDFWAPQiTunhS6UX8fEonrd1ONahV+6Qz/PKxxSULhTlS/9KiIFW6YXbZFkTK3H+pAYnz0FziL5I7rUm5Mpic49AiMFNAM56ZD02CFShl4c1cX56eeCJoodU3bDKCvZ3pOLr/jljMsH0llWgO1PfAnYbzE3pSeNfmRN9DjQ8fOV4O2eSDpaWMiiDd6UGyhu/CcQMlNL3A3YPkbZa6QpwfNhTZdgaHmX9XbFRieLcYI2BxeRStImISIVjtztARUnvXX7NVyjzxPqUTOtuUF+Ge2TjAEikRVdz508npZ+FK/GaIfViZOlWtBjkFXmCmjoVF8eGmntO7xyh1POHRnI98rYEXv6EBtdKEOegCC0q4q9GX8vs0WqZgR2PNAGkOMqWn5PHLqhdlTsf/fHQS+10tVGGcQzat1GKnXDjAs7l+w0=
before_install:
- ruby -v
- gem install travis -v 1.8.9 --no-document
- export BUILD_NAME=scc-icad-service-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
jobs:
  include:
  - stage: build and deploy
    script:
    - sh scripts/travis/tag_build.sh
    - sh scripts/travis/build_services.sh
    - sh scripts/travis/deploy_to_docker_hub.sh
stages:
- name: build and deploy
  if: branch = master
env:
  global:
  - secure: VLs1zr5KlYVHgP9kenIgaxk1d07+VcHZmLPE1k2gTIkSbVm3aBLCeT/Itn57NYGr2X0FHcC9bnX7+OQ2M5BTyBx6lWo6tO3O9W4x0PSnyJnxrh07ZpGcjmcHYC5aUy/7MLBVac1PrD8NGStoykVgxUHECJpIAt2wYugqG23YgKsBdXoirowHOMym1oy5CpLrhpDpoY3lZtaG2Sw+GBaT8q8lsQvOxxAxkC9nrgrw1KO3afHzaAMLnPZCaX639TnRx4y3yV2zpvPxBg47stZZBZoGfwWfM18VhmdSRhLpz0ZfaHF9tM6q3ZWp8jhY4zg1P2IC4byerd8kEqQRAvvV+QkEHpolKvO6Ox/Zqpx0VbuUwhoZX0dMcbJDKailrXIwwxTR0GyjT39ytSh6DZG6p1t2RpJFZvvmCaENdtjhrIBwZFXfdQ2BONweNHLosYVsVzFJRuTJM0kTgoSS5ex+R4a2swMdXq25+Bd62DY3eNxzW95U+VYmx/lL4cQ/v0QoFsG+8EB9IVZP5L2U5xaG1DQqYePEa/FynZzwmTwCacHIFfMGh8JMPLzMw9/wfU40d+B1wdeyipFQgY7iJHlc35HSiciH2MPKarswnxuFNpUYCB1SNiWijBneqaWt/sUUB3TWlkFgjOfzc2WC2upSoo6OVQe9XB/NT6O+XmozRbU=
  - secure: ShJkx5/zlR1BjX9anRWDnDgbrzq6oURojo2makIzuFeCJlEZi97MPG2nidK6sGXfr+lgkLiynrZDOL6D29McroC5p4R+foSQzWnAFU2J/QrAh5MGM5PqS3aCEMOWvnQeCkOeyOiWdOeizflcV1g1uQYvLd3ER5NkRsUycptzm66fjbKwIYiPmmDiYktXPsQ+WClp9yM2y38MzanmtizaPWxW+xCqrzl02mYwYU7io+lmApKcQyGaiufFphK4/aYJ/nGuqwCyDoDBPsn8Osxwz/bAqSqbonGE4yGQnqryDqZdwNTHIrNCmkBQYXKIeTmdgiwxgyqsAdF30IqwjtDm3J5yT8FtNfxpZGnbHFoS7Sq1IQ62mV4Bbo72ZWJq0aJWSxZpPBRYZVVfU89DT0Psp1IwxOxQ5XBDza/TiWxGyh7U0OdAXR6YOv9hndWCAZYTOwuxiHWlLo4W2f275mN44lOrG58uXntMVV8qyaml71B8Gz/hupgBqIn7HfEwYDSAyyA3al8gcrAlWGtlNQh6PRjdoCw3TUrEkVxXcey+sGvUX3PHjmgUa5EnzwCmhZYj4C1Zh3+YP8s/Ku3N/54cAdz7kmtnmHZH9RP+Zj/N9HTbac1pMJHTZE2W1vEEeBELaVCLTaTsBMl4m8Rnrf1o4KtS4RdUYtq0Bt8M7dzkydU=
  - secure: PwP1jdLZMWchDPAbqp/adc5/FoclQyYzNy+qu8LoPEPXeBeiNrchrH86A4uOCwsB1QDIsQFWHktvipWnOLHrNIofpKWaEQ9qZe/1GSubtMSAuae9DTJbMmY73JVax0+i7Ae70gERb7uAc2gr4XLkq55kBgd9jjWXnHLBrcUX4hD8znmpfDJ8KiJA9Dw7AinFswd1YMJxf2/IqxBkTgInmyHI3DRGI3T7y41y8pECvTVN2yZTwNagj9gEBBWcmBvAOz9UsOlWqxx+qfs5j3h8/3J4rOBSQqiRiZeP0Y8SiA2UrcuJz49Gj+Aczu/HXUOAdS5caaoof3tnp7MIq3H+fRKN2+OYo1HLgePT3+rPyHyNEReGTDncfmapH++sd52/Ea34mggLk7F50eRHlpREPrJwXuxSZmefuUn4ePdWWJgyKqg8s8VlYly29D4QxokxShbRG1wykgcL0+Qg0jO457FPsn7k967apsjg7Gj3DDhLyzqKTAWficp+dEsUyy8Yy99yboV+cZF+WUzw/rTnMsfJyJgDMY2UNdoMxewP2CrdFyci/mE2HaNuuOQZsLPd8FGi9S1QrD7XfSbAaPT0pMDD7aJKHhAcn3AC9ugIDzqhMNVXZNsC1x0zs4AqBxNyonHztSV5/IRcq4I73WQGiH0n1fKZcpURyR/LX+taD4Y=
