#Default port is 8092
server:
  port: 8092
  
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  zipkin:
    baseUrl:  http://localhost:9411

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
                